name: vocabify

services:
  db:
    extends:
      file: .docker/compose.base.yml
      service: db
    ports:
      - '5432:5432'
    volumes:
      - ${PWD}/.docker/volumes/pg_data:/var/lib/postgresql/data
    networks:
      - vocabify_network
    
  redis:
    extends:
      file: .docker/compose.base.yml
      service: redis
    ports:
      - '6379:6379'
    volumes:
      - ${PWD}/.docker/volumes/redis_data:/data
    command: ["redis-server", "--appendonly", "yes", "--dir", "/data"]
    networks:
      - vocabify_network

  
  qdrant:
    extends:
      file: .docker/compose.base.yml
      service: qdrant
    ports:
      - '6333:6333'
    volumes:
      - ${PWD}/.docker/volumes/qdrant_data:/qdrant/storage
    networks:
      - vocabify_network


volumes:
  pg_data:
  redis_data:
  qdrant_data:

networks:
  vocabify_network:
