name: vocabify

services:
  node:
    build:
      context: .
      dockerfile: .docker/Dockerfile.dev
    extends:
      file: .docker/compose.base.yml
      service: node
    ports:
      - '${APP_PORT}:${APP_PORT}'
    volumes:
      - ${PWD}:/app
    depends_on:
      - db
      - redis
    networks:
      - vocabify_network

  db:
    extends:
      file: .docker/compose.base.yml
      service: db
    ports:
      - '${DB_PORT}:${DB_PORT}'
    volumes:
      - ${PWD}/.docker/volumes/pg_data:/var/lib/postgresql/data
    networks:
      - vocabify_network
    
  redis:
    extends:
      file: .docker/compose.base.yml
      service: redis
    ports:
      - '${REDIS_PORT}:${REDIS_PORT}'
    volumes:
      - ${PWD}/.docker/volumes/redis_data:/data
    command: ["redis-server", "--appendonly", "yes", "--dir", "/data"]
    networks:
      - vocabify_network

  qdrant:
    extends:
      file: .docker/compose.base.yml
      service: qdrant
    ports:
      - '${VECTOR_DB_PORT}:${VECTOR_DB_PORT}'
    volumes:
      - ${PWD}/.docker/volumes/qdrant_data:/qdrant/storage
    networks:
      - vocabify_network

volumes:
  pg_data:
  redis_data:

networks:
  vocabify_network:
