services:
  node:
    container_name: node
    tty: true
    working_dir: /app
    restart: unless-stopped

  db:
    image: postgres:16-alpine
    container_name: db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    restart: unless-stopped

  redis:
    image: redis:8-alpine
    container_name: redis
    restart: unless-stopped

  qdrant:
    image: qdrant/qdrant:dev
    container_name: qdrant
    restart: unless-stopped