services:
  node:
    container_name: node
    tty: true
    working_dir: /app
    restart: unless-stopped

  db:
    image: postgres:16-alpine
    container_name: db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_DATABASE}"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  redis:
    image: redis:8-alpine
    container_name: redis
    restart: unless-stopped

  qdrant:
    image: qdrant/qdrant:dev
    container_name: qdrant
    restart: unless-stopped

  caddy:
    image: caddy:2.11-alpine
    container_name: caddy
    restart: unless-stopped